# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)^(
    gradlew |
    gradlew.bat
  )$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-xml
  - id: check-yaml
  - id: check-added-large-files
# TODO(hodol, 250515): Move local hooks into any separate repo.
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: shfmt
    args: [-w, -i=2, -sr, -ci]
  - id: shellcheck
- repo: local
  hooks:
    - id: gradle-spotless
      name: Spotless changed files only
      entry: tools/apply-spotless.sh
      language: script
